import React from "react";
import { MDBRow, MDBCol,MDBContainer } from "mdbreact";
import './term-page.scss';
import Dialog from '@material-ui/core/Dialog';
import DialogTitle from '@material-ui/core/DialogTitle';
import CloseIcon from '@material-ui/icons/Close';
import IconButton from '@material-ui/core/IconButton';
import Typography from '@material-ui/core/Typography';
function Term1(props){
    return(
    <Dialog fullScreen
    aria-labelledby="alert-title"
    open={props.openTerm}
    onClose={props.closeTerm}
     classes={{ paperScrollPaper: 'dialogclass' }}>
        <div className="gutterareapop">
            <IconButton aria-label="Click Here to Close" edge="start" color="inherit" onClick={props.closeTerm}>
                <CloseIcon />
            </IconButton>
        </div>
        <Typography variant="h6" color="inherit" id="alert-title"></Typography>
            <MDBContainer>
                <MDBRow className="text-left term-page">
                <MDBCol size="12">
                        <h1>Terms & Conditions </h1>
                        <p>These Terms and Conditions govern your access to and use of Southwest Gas Corporation's ("Southwest Gas") owned and operated website, mobile application, text messaging service, email service, Southwest Gas-branded social media, and any Southwest Gas online platform ("Online Services").</p>
                        <p>By accessing Southwest Gas' Online Services, you agree to be bound by these Terms and Conditions. If you do not agree to these Terms and Conditions, you should not use Southwest Gas' Online Services.</p>
                        <p><u>THIS AGREEMENT CONTAINS A MANDATORY DISPUTE RESOLUTION PROVISION THAT REQUIRES THE USE OF PUBLIC UTILITIES COMMISSIONS OR ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS.</u></p>
                        <h2>Device Compatibility</h2>
                        <p>Our Online Services function on certain devices and operating systems. You acknowledge that your operating system and future operating system upgrades to your device may or may not be compatible with our Online Services. You are solely responsible for all message and data charges that you incur. Please contact your mobile service provider about such charges.</p>
                        <h2>Service Fees and Additional Charges</h2>
                        <p>You are responsible for any and all telephone and/or mobile carrier access fees, text messaging fees, data usage fees, and/or Internet service fees that may be assessed by your telephone, mobile carrier, and/or Internet service provider as a result of using any of Southwest Gas' Online Services.</p>
                        <h2>MyAccount Management Usage Agreement</h2>
                        <p>You may use Southwest Gas' online utility bill account access system ("MyAccount") only if you are a customer of Southwest Gas and have agreed to participate in MyAccount by properly registering username and password consistent with these Terms and Conditions. MyAccount may be accessed by certain Online Services, including Southwest Gas' website and mobile application.</p>
                        <h3>MyAccount Management Service</h3>
                        <p>MyAccount allows you to access online services specific to your Southwest Gas account(s). Online services under the MyAccount umbrella include online billing and payment information/services, as well as other account-related information and analysis tools. Southwest Gas may add additional online services to MyAccount, as appropriate, in the future.</p>
                        <p>Southwest Gas reserves the right to modify or discontinue any or all services or features of MyAccount at any time, without notice, or to offer specific programs only to customers meeting applicable qualifications. Subject to satisfying the qualifications for a particular program, you may elect to use one or more of the features available without being obligated to use them all.</p>
                        <h3>Customer Requirements</h3>
                        <p>Specifically, by participating in MyAccount you agree that:</p>
                        <p>You are subject to these Terms and Conditions until such time that your MyAccount, including all its online services, is discontinued. By clicking the “Register” button when registering for MyAccount, you are confirming that you accept these Terms and Conditions (including any future modifications thereof) as a pre-condition to access to MyAccount. When you meet the above requirements, you will receive an email message from Southwest Gas confirming your registration in MyAccount.</p>
                        <h3>Password Guidelines</h3>
                        <p>The unique username and password (collectively, "Password") selected by you to access MyAccount must be held on a confidential basis. Anyone with knowledge of your Password can gain access to MyAccount and all the services available within the account. If you have forgotten or lost your Password, online services are available to assist you in resetting it. If you need assistance, contact Southwest Gas by email or by calling Customer Solutions at 877-860-6020, Monday-Friday 7 a.m. - 6 p.m. PST (excluding holidays). You are responsible for maintaining the Password against improper disclosure. One of the terms and conditions of this agreement is that you are solely responsible for any claims, losses, damages, expenses and costs incurred by the use of your Password by others. Southwest Gas reserves the right to reset any Passwords.</p>
                        <h3>Emails from Southwest Gas</h3>
                        <p>By registering for MyAccount, you agree to receive automatic email notifications related to online services, MyAccount and/or your natural gas account. Additionally, you may receive notifications via email regarding construction and maintenance updates, activities pertaining to our programs or services, providing surveys to help improve our customer service, notifying customers of special events, sharing energy and safety education information, and providing offers related to our products and services that may be of interest to you.</p>
                        <h3>Contact Information</h3>
                        <p>As a MyAccount user, it is your responsibility to ensure that the contact and other required information in your user profile is current and accurate, and updated promptly if necessary, including your name, address, phone number and email address. Changes can be made within the MyAccount service or by contacting Southwest Gas via email or calling Customer Solutions at 877-860-6020, Monday-Friday 7 a.m. - 6 p.m. PST (excluding holidays).</p>
                        <h3>Discontinuing MyAccount (online account access)</h3>
                        <p>Discontinuing MyAccount will no longer allow you access to online services specific to your Southwest Gas account(s).</p>
                        <h2>Automatic Payment Plan</h2>
                        <h3>Program Qualifications and Restrictions</h3>
                        <p>Residential and Commercial customers are eligible for enrollment in Southwest Gas' Automatic Payment Plan ("APP") if the following requirements are met:</p>
                        <p>You must have a current/valid U.S. bank account at a financial institution where the payment will be withdrawn.</p>
                        <p>Your Southwest Gas account must be an active account and your account must not have been removed from the APP by Southwest Gas in the past twelve (12) months.</p>
                        <h3>Your Commitment to Us</h3>
                        <p>It is your responsibility to:</p>
                        <p>Ensure there are sufficient funds available in your checking or savings account to meet each withdrawal on the due date. If there are insufficient funds in your account, your financial institution and Southwest Gas may charge you a fee and/or interest. You are solely responsible for paying any fee and/or interest charged by your financial institution or Southwest Gas. Check your account statement to verify that the amounts debited from your account are correct.</p>
                        <p>Advise us if the payment account is transferred or closed, or if the account details change no later than two (2) business days before the debit date.</p>
                        <p>Arrange an alternate payment method if you cancel the scheduled withdrawal.</p>
                        <h3>Payment Obligations</h3>
                        <p>On your due date, our third-party vendor will deduct your APP payment from the payment account you designate. Your billing statement will indicate that it is being paid through the APP when this service is activated. In the event that Southwest Gas makes a billing adjustment to the account, Southwest Gas will cancel the withdrawal and establish a new withdrawal for the amount and due date as indicated on the revised bill.</p>
                        <p>If two requests are returned for insufficient funds, you may be excluded from using the APP to make payment. If you need to update your checking or savings account information, you can do so online through MyAccount. However, to the extent this information requires updating, and such updates are not made prior to the applicable payment deadline (as discussed in detail above), all applicable additional charges, including, but not limited to, late fees, may be assessed. If the transaction is refused by your financial institution for any reason, including, but not limited to, insufficient funds, closed account, or unauthorized account, Southwest Gas will not be able to process your payment. Your Southwest Gas account may be subject to additional charges if your payment is rejected, reversed or refused by your financial institution.</p>
                        <h3>Cancellation</h3>
                        <p>To cancel an APP withdrawal, you will need to notify Southwest Gas at least two (2) business days before the transaction is scheduled to occur.</p>
                        <h3>Termination</h3>
                        <p>Participation in Southwest Gas' APP is completely optional. We reserve the right to discontinue accepting APP payments at any time, for any reason without prior notice. We may send notification of termination of APP any time after the termination is effective. We also may temporarily discontinue accepting APP payments, within our sole discretion. Termination does not affect your rights and obligations for APP payments prior to termination.</p>
                        <p>These Terms and Conditions do not supersede, modify or in any way mitigate your obligation to be bound by and comply with the Southwest Gas MyAccount Terms and Conditions.</p>
                        <h2>Paperless Billing</h2>
                        <h3>Enrollment Requirements</h3>
                        <p>The Paperless Billing option requires an active Southwest Gas account number, a valid email address and to be logged into or create a "MyAccount". You may enroll in Paperless Billing at any time.</p>
                        <h3>Bill Delivery and Presentment</h3>
                        <p>Upon enrollment in Paperless Billing, one last paper bill may be presented. In addition to your paperless bills, disconnect, final, and special billings will be mailed.</p>
                        <h3>Notification</h3>
                        <p>Southwest Gas will use its best efforts to present all of your paperless bills promptly. Southwest Gas will send email notification to the email address listed on your account. It is your sole responsibility to ensure that this information is accurate. In the event you do not receive notification, it is your responsibility to log into MyAccount and check on your paperless bills and account balance(s).</p>
                        <h3>Payment of Bills</h3>
                        <p>It is your sole responsibility to pay your Southwest Gas bill on time to avoid late fees, collection activity or disconnection of service.</p>
                        <h3>Termination/Cancellation of Paperless Billing</h3>
                        <p>You may terminate Paperless Billing at any time by logging into MyAccount. After you terminate Paperless Billing, future bills will be mailed to your current address on file with Southwest Gas. Please make sure to pay your final paperless bill by the due date. You can check your current account balance at <a aria-label="Navigate to myaccount swgas" href="https://myaccount.swgas.com/">https://myaccount.swgas.com/</a>.</p>
                        <h3>Cancellation of Paperless Billing</h3>
                        <p>Southwest Gas reserves the right to cancel the presentment of Paperless Billing at any time.</p>
                        <h3>Non-Delivery of Paperless Billing(s)</h3>
                        <p>If emails are returned as undeliverable to Southwest Gas, Southwest Gas reserves the right to terminate you from Paperless Billing and return to sending you a paper bill. You may enroll again at any time after correcting any email address errors through MyAccount.</p>
                        <h3>Questions and Disputes</h3>
                        <p>In case of questions regarding your Paperless Billing transactions, contact Southwest Gas by <a aria-label="Navigate to Contact us" href="https://www.swgas.com/en/contact-us">email</a> or by calling Customer Solutions at 877-860-6020, Monday-Friday 7 a.m. - 6 p.m. PST (excluding holidays).</p>
                        <p>These Terms and Conditions do not alter your liability or obligations that currently exist between you and Southwest Gas concerning your utility usage, and other products and services. Neither termination nor cancellation shall affect your liability or obligations under these Terms and Conditions.</p>
                        <h2>Address Changes</h2>
                        <p>It is your sole responsibility to ensure that the contact information in your user profile is current and accurate. This includes, but is not limited to; name, address, phone number(s) and email address(es). Changes can be made either within the application or by contacting Customer Solutions.</p>
                        <h2>Information Verification</h2>
                        <p>You agree that the information you provide to Southwest Gas can go through a verification process.</p>
                        <h2>Online Payment</h2>
                        <p>Program Qualifications and Restrictions</p>
                        <p>Eligible Residential and Commercial customers are permitted to utilize Southwest Gas' Online Payment service ("Online Payment") via MyAccount if the following requirements are met:</p>
                        <p>You must have a current/valid U.S. bank account at a financial institution, or a valid credit or debit card where the payment will be withdrawn. Payments will be withdrawn by our third-party vendor on the date specified.  </p>
                        <p>Your Southwest Gas account must be active or have a balance owing.</p>
                        <h3>Customer Requirements</h3>
                        <p>By clicking the (submit button)"I Accept, Submit Online Payment" button on the website or "I Agree, Submit Payment" on the mobile application, you are confirming that you accept these Terms and Conditions (and any future modifications thereof) and agree that by scheduling a payment via Online Payment, you authorize your financial institution and Southwest Gas to initiate debit(s), credit(s) or correction entries for such payments. Your acceptance of these Terms and Conditions is an affirmative representation that you have all necessary rights, power and authority to authorize each such payment and that you will take such steps as your financial institution requires to make such authorization.</p>
                        <h3>Your Commitment to Us</h3>
                        <p>It is your responsibility to:</p>
                        <p>Ensure there are sufficient funds available in your checking or savings account to meet each scheduled Online Payment. If there are insufficient funds in your account, your financial institution and Southwest Gas may charge you a fee and/or interest. You are solely responsible for paying any fee and/or interest charged by your financial institution or Southwest Gas. Check your bank account statement to verify that the amounts debited from your account are correct. Any overpayments resulting in a credit balance cannot be refunded but will be applied as a credit on your Southwest Gas account. Requests for refunds due to overpayment should be directed to your financial institution which may charge a fee associated with the refund request.</p>
                        <h3>Payment Obligations</h3>
                        <p>Payments made Monday through Friday before 6pm Pacific Time will post to your account the same day. Payments made after 6pm, or on weekends or holidays, will post to your account on the next business day. (Business days are Monday through Friday, except for banking holidays.) Please ensure that your payment is made prior to 6pm on or before the due date of the bill. You are solely responsible for making payments prior to the due date, and you are solely responsible for any late fees charged by Southwest Gas for payments not made timely. Late fees for any payments made using Online Payment are the same as the late fees charged for mailed payments. Online Payment is designed to be available seven days a week, 24 hours a day, and Southwest Gas will endeavor to update account balance and activity information daily. However, Southwest Gas shall not be liable for any inability to access Online Payment, or for Southwest Gas' failure to update any information, for whatever reason.</p>
                        <p>Southwest Gas does not charge you a convenience fee for using Online Payment. However, your financial institution and/or our third-party vendors, may charge you fees related to your scheduled payment, including convenience fees, transaction fees, or fees for attempting payments without sufficient funds. If the transaction is refused by your financial institution for any reason, including, but not limited to, insufficient funds, closed account, or unauthorized account, Southwest Gas will not be able to process your payment. Your Southwest Gas account may be subject to additional charges if your payment is rejected, reversed or refused by your financial institution.</p>
                        <p>If you save your banking information for reoccurring use in MyAccount, and need to update your checking or savings account information, you can do so online through MyAccount or on the mobile application. However, to the extent this information requires updating, and such updates are not made prior to the applicable payment deadline (as discussed in detail above), all applicable additional charges, including, but not limited to, late fees, may be assessed.</p>
                        <p>The Company does not and will not collect nor sell your personal information for commercial purposes to third parties nor disclose your personal information to third parties for the purpose of telemarketing, email or direct mail solicitation. To submit a formal request to opt out of any potential future sale of personally identifiable information the Company has collected or will collect about you, please send an email including your full name (as it appears on your SWG account), service address, and your full account number to optout@swgas.com </p>
                        <h3>Unauthorized or Disputed Payments</h3>
                        <p>If you believe that someone has made an unauthorized payment through Online Payment without your permission, contact your financial institution immediately. You are solely responsible for any unauthorized payments, although your financial institution may provide some form of fraud protection.</p>
                        <p>In case of disputes or questions about your Online Payment, contact Southwest Gas by <a aria-label="Navigate to contact us" href="https://www.swgas.com/en/contact-us">email</a> or by calling Customer Solutions at 877-860-6020, Monday-Friday 7 a.m. - 6 p.m. PST (excluding holidays). Southwest Gas must hear from you within sixty (60) days after the first bank statement on which the problem appeared was sent to you. Please provide your name and Southwest Gas account number, describe the error or transfer about which you are unsure, why you believe there is an error, and the dollar amount of the suspected error.</p>
                        <p>Southwest Gas will inform you as to the result of the investigation within ten (10) business days after Southwest Gas hears from you and will correct any error promptly. If more time is needed, however, Southwest Gas may take up to forty-five (45) days to investigate your complaint or questions. If no error is found, Southwest Gas will contact you within three (3) business days after the investigation is completed.</p>
                        <h3>Termination</h3>
                        <p>Participation in Southwest Gas' Online Payment is completely optional. Southwest Gas reserves the right to suspend or discontinue accepting online payments at any time, for any reason without prior notice. Southwest Gas will attempt to provide you with prior notice of suspension or termination of Online Payment, but Southwest Gas will not be liable for any failure to do so. Neither termination nor discontinuation of Online Payment shall affect your liability for transactions initiated through this service.</p>
                        <h2>Service Order</h2>
                        <p>In submitting a service request you, the customer, agree to take and pay for gas service from Southwest Gas in accordance with this application including the above clause(s) hereof and the rates, terms and conditions contained in Southwest Gas' tariffs as amended from time to time and available for inspection at any business office of Southwest Gas and at <a aria-label="Navigate to rates and regulation" href="https://www.swgas.com/en/rates-and-regulation">https://www.swgas.com/en/rates-and-regulation</a>.</p>
                        <h2>Location-Based Services</h2>
                        <p>Southwest Gas provides location services, within its mobile application, that enable a customer's mobile device location to be determined. Please see our <a aria-label="Navigate to privacy policy" href="https://www.swgas.com/en/privacy-policy">Privacy Policy</a> for information on what location-based data we collect as a result of use of our location-based services.</p>
                        <p>Location services are an integral part of certain Southwest Gas services, enabling customers' mobile device location information to be displayed on a map, be associated with received messages, and included with alerts, status and service request updates.</p>
                        <p>The mobile device and/or software application on the mobile device will allow the customer to enable or disable location services.</p>
                        <p>The following terms of use apply for location services:</p>
                        <ol type="1">
                            <li>In order for the location-based aspect of a service to operate correctly, Southwest Gas, or a third-party vendor, must be permitted to communicate with your phone/tablet and or computer. By doing so, Southwest Gas will attempt to identify your location. This may require the collection, use and sharing, among other things of precise coordinate data, including real time geographic location of your device with Southwest Gas partners, licensors and licensees, in accordance with the terms as set out in our Privacy Policy. The subject location information is captured when the customer uses location services and will not be used outside of the customer's use of the location service.</li>
                            <li>You expressly agree, by using location services, that you authorize Southwest Gas, to collect and use your location data as a part of Southwest Gas' services. Where applicable, you may at any time disconnect your device from the location-based aspect of the services.</li>
                            <li>Southwest Gas does not represent that its location services are suitable for emergency situations and should not be relied upon as such. Southwest Gas shall not be liable for any reliance placed by an individual on its locational services, especially in the event of death or serious injury.</li>
                            <li>You shall be responsible for managing the processing, use and security of location information. You must use the location service associated location information within the law and acknowledges that the collection and use of sensitive personal data using location information is subject to relevant privacy and data protection laws.</li>
                            <li>You accept that the service accuracy of the location information can vary depending on your situation, i.e. city versus country location.</li>
                            <li>Where Southwest Gas has reasonable grounds for suspecting misuse of the location service or failure by the customer to either follow such instructions or adhere to Southwest Gas' Terms and Conditions may result in Southwest Gas suspending the location service, and for repeated misuse or failures may result in location service being withdrawn.</li>
                        </ol>
                        <h2>Push Notifications</h2>
                        <p>We may provide you with push notifications, alerts and other messages related to the mobile application and/or Southwest Gas' services. After downloading Southwest Gas' mobile application, push notifications/alerts will be automatically sent to you. If you no longer wish to receive push notifications/alerts from the mobile application, you may opt out by changing the notification settings on your mobile device.</p>
                        <h2>Electronic Mail (Email) and Fax Communication</h2>
                        <p>The information in electronic mail (email) or fax communication and from Southwest Gas may contain confidential information, which is the property of the sender. Email or fax communication from Southwest Gas is intended solely for the addressee and access by anyone else is not authorized. If you are not the intended recipient, you are hereby notified that any disclosure, copying, or distribution of the contents of an email or fax transmission from Southwest Gas or the taking or omission of any action in reliance thereon or pursuant thereto, is prohibited, and may be unlawful. If you receive an email or fax from Southwest Gas in error, please notify us immediately by email and destroy the communication, any attachments, and all copies thereof. Southwest Gas does not guarantee the privacy or security of information transmitted by facsimile (fax) or other unsecure electronic means (including email). By choosing to send or receive information, including confidential or personal identifying information, via fax or unencrypted email, you consent to accept any associated risk.</p>
                        <h3>Billing/Payment Email Notifications</h3>
                        <p>You can opt in or opt out of additional email notifications regarding payment reminders and your bill status, by going to the "Notification Preferences" in the "Settings" menu at <a aria-label="Navigate to myaccount swgas" href="https://myaccount.swgas.com">https://myaccount.swgas.com </a> or via the Notification Preferences section of the Southwest Gas mobile app.</p>
                        <p>Failure to deliver billing or payment reminders does not modify or absolve your payment obligations. In the event you do not receive a payment reminder, it is your responsibility to log into MyAccount and check on your paperless bills and account balance(s).</p>
                        <p>Changes made to your "Billing/Payment Notification Preferences" do not affect your enrollment status in paperless billing and will not change the email address associated with your MyAccount, nor prevent SWG from sending email communications related to your MyAccount.</p>
                        <h2>Text Message-Specific Terms and Conditions</h2>
                        <p>Your access to, and use of, the mobile communication tools and text messaging services (collectively, "SWG text service") is subject to these Terms and Conditions and all applicable laws and regulations. By opting in to text notifications on MyAccount web or mobile, accessing and using SMS or MMS texting, entering prompts to opt in during a call with our automated telephone system, and/or providing verbal consent to a Southwest Gas customer service representative, you accept, without limitation or qualification, these Terms and Conditions.</p>
                        <p>Southwest Gas offers access to account information, billing and payment notifications, service related information (e.g., threatened interruptions of service, actual interruptions of service, and service restoration information), programs, and natural gas safety messages via recurring SMS, MMS text alerts, and pre-recorded and auto-dialed calls. Enrollment in our text alerts service is limited to Southwest Gas customers and their authorized designees. Enrollment requires a customer (or their designee) to provide his or her own mobile phone number with an area code within the 50 United States or the District of Columbia. By enrolling in our text alerts service, you agree to these Terms and Conditions, which become effective immediately upon your enrollment.</p>
                        <p>You acknowledge that text alerts will be sent to the mobile phone number you provide to the Company. Such text alerts may include limited personal information about your account. You acknowledge that anyone with access to your mobile phone or carrier account will also be able to see this information. Once you enroll, the frequency of text alerts we send to you will vary. You will typically receive text alerts when we have information for you about your account and interruptions of service.</p>
                        <p>To manage your text notification preferences and contact information, go to your "Notification Preferences" in the "Settings" menu at <a href="https://myaccount.swgas.com">https://myaccount.swgas.com</a> or the Notification Preferences section of the Southwest Gas mobile app.</p>
                        <p>Participation in our text alerts service is not required for gas service.</p>
                        <p>You acknowledge and understand that messages are sent without encryption, which presents some security risk.</p>
                        <h3>Termination</h3>
                        <p>You may opt out of the SWG text alerts service at any time. To stop receiving Company text alerts, text STOP to the number upon which you are receiving Company text alerts. Texting STOP to the number you are receiving Company text alerts from will opt you out of any and all future Company text messages. Alternatively, you may opt out of our text alerts service by managing your Notification Preferences at https://myaccount.swgas.com or calling the Company's Customer Solutions Department during business hours at 877-860-6020.</p>
                        <p>After you submit a request to unsubscribe, you will receive one final text alert from Company confirming that you will no longer receive Company text alerts. No additional Company text alerts will be sent unless you reactivate your enrollment to the SWG text alerts service by texting START to the number upon which you are receiving Company text alerts or by managing your Notification Preferences at https://myaccount.swgas.com.</p>
                        <p>The Company reserves the right, in its sole discretion, to cancel or suspend any or all SMS texting, MMS texting, and/or pre-recorded and auto-dialed calls in whole or in part, for any reason, with or without notice to you.</p>
                        <h3>Texting Commands</h3>
                        <p>For questions about our text alerts service, text the word HELP to the number you are receiving Company text alerts from. Company text alerts may come from short codes and the Company may change, add or remove short codes as necessary.</p>
                        <h3>Text Quiet Hours</h3>
                        <p>You may opt in to "Text Quiet Hours" for "Billing and Payment" notifications. By opting in, you request that SWG not send "Billing and Payment" related text notifications between the "From" and "To" timeframe you select. For text notifications scheduled to be sent during the customer selected "Text Quiet Hours," the text will be held and sent after the "Text Quiet Hours" period is over. Text quiet hours are implemented for the time zone that the associated Service Address is located in.</p>
                        <h3>No Warranties</h3>
                        <p>SOUTHWEST GAS' TEXT ALERTS SERVICE IS OFFERED ON AN "AS IS" BASIS AND: (1) MAY NOT BE AVAILABLE IN ALL AREAS AT ALL TIMES; AND (2) MAY NOT CONTINUE TO WORK IN THE EVENT OF PRODUCT, SOFTWARE, COVERAGE OR OTHER SERVICE CHANGES MADE BY YOUR WIRELESS CARRIER. THE COMPANY MAY CHANGE OR DISCONTINUE ANY PORTION OF ITS TEXT ALERTS SERVICE WITHOUT NOTICE OR LIABILITY TO YOU.</p>
                        <p>THE COMPANY RESERVES THE RIGHT TO CEASE DELIVERY OF TEXT ALERTS TO ANY PERSON AT ANY TIME IN ITS SOLE DISCRETION.</p>
                        <p>WE DO NOT GUARANTEE THAT THE USE OF SMS TEXTING, MMS TEXTING, OR AND PRE-RECORDED AND AUTO-DIALED CALLS WILL MEET YOUR PERFORMANCE REQUIREMENTS OR BE UNINTERRUPTED OR ERROR-FREE. WE MAKE NO WARRANTIES OR REPRESENTATIONS AS TO THE USE OR RESULTS OF USE IN TERMS OF SECURITY, DATA PRIVACY, DATA LOSS, CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. WE WILL NOT CORRECT ANY ERRORS RELATED TO YOUR USE OF SMS TEXTING, MMS TEXTING, OR AND PRE-RECORDED AND AUTO-DIALED CALLS. YOU ASSUME ALL RISKS AS TO THE QUALITY AND PERFORMANCE OF SMS AND MMS TEXTING, INCLUDING BUT NOT LIMITED TO HEALTH RISKS. YOU ACKNOWLEDGE AND AGREE THAT YOU ARE SOLELY RESPONSIBLE FOR ANY DEATH, PERSONAL INJURY, OR ENVIRONMENTAL DAMAGE YOU CAUSE TO YOURSELF, OR OTHERS, BY YOUR USE OF SMS TEXTING, MMS TEXTING, OR PRE-RECORDED AND AUTO-DIALED CALLS.</p>
                        <p>SMS TEXTING, MMS TEXTING, AND ALL PRE-RECORDED AND AUTO-DIALED CALLS ARE PROVIDED TO YOU "AS IS," AND TO THE EXTENT PERMITTED BY LAW, THE COMPANY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE. NO STATEMENTS FROM THE COMPANY OR ITS EMPLOYEES, DEALERS OR AGENTS MAY INCREASE THE SCOPE OF THE ABOVE WARRANTIES OR CREATE ANY NEW WARRANTIES. IF THIS DISCLAIMER IS INVALID UNDER APPLICABLE LAW, ANY IMPLIED WARRANTIES ARE LIMITED IN DURATION TO THIRTY (30) DAYS FROM THE DATE THAT YOU FIRST USE OUR TEXT ALERTS SYSTEM.</p>
                        <h3>Limitation on Liability</h3>
                        <p>YOU AGREE THAT THE COMPANY AND ITS PARENT AND SUBSIDIARY COMPANIES, AND EACH OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, LOWER-TIERED CONTRACTORS, CONSULTANTS, LICENSORS AND SUPPLIERS ARE NOT RESPONSIBLE AND SHALL NOT BE LIABLE FOR ANY LOSSES OR INJURIES OF ANY KIND RESULTING, DIRECTLY OR INDIRECTLY, FROM OUR TEXT ALERTS SERVICE OR FROM TECHNICAL FAILURES OR DELAYS OF ANY KIND. THIS AGREEMENT OF NON-LIABILTY EXTENDS TO ALL DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, AND EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOST PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILTY OF SUCH DAMAGES, RESULTING FROM THE OPERATION, USE, OR THE INABILITY TO USE OUR TEXT ALERTS SERVICE, FROM THE UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA, STATEMENTS OR CONDUCT OF ANY THIRD PARTY REGARDING SMS TEXTING, MMS TEXTING OR PRE-RECORDED AND AUTO-DIALED CALLS, OR ANY OTHER MATTER RELATED TO SMS TEXTING, MMS TEXTING OR PRE-RECORDED AND AUTO-DIALED CALLS.</p>
                        <h3>Reports of Emergency Conditions to the Company</h3>
                        <p>YOU AGREE THAT YOU WILL NOT SEND EMERGENCY NOTIFICATIONS OR MESSAGES, SUCH AS REPORTING THE PRESENCE OF A KNOWN OR SUSPECTED GAS LEAK, TO THE COMPANY BY SMS OR MMS TEXT. YOU AGREE THAT ANY REPLY FROM THE COMPANY TO SUCH A MESSAGE, OR THE ABSENCE OF A REPLY FROM THE COMPANY TO SUCH A MESSAGE SHALL BE CONSTRUED AS THE FAILURE OF THE COMPANY TO RECEIVE YOUR EMERGENCY MESSAGE. YOU AGREE THAT IF YOU SMELL GAS OR OTHERWISE SUSPECT A GAS LEAK, YOU WILL CALL 911 AND THE COMPANY AT 877-860-6020.</p>
                        <h3>License</h3>
                        <p>Your use of our text alerts service is pursuant to a limited, non-exclusive, revocable license and is subject to this Agreement and the <a aria-label="Navigate to privacy policy" href="https://www.swgas.com/en/privacy-policy">Company's Privacy Policy</a>, either of which may be amended periodically by the Company without prior notice to you. If you do not agree, you may not establish or use our text alerts service.</p>
                        <h2>Other Terms and Conditions</h2>
                        <p>Southwest Gas has no responsibility for any failure or error in its Online Services and/or MyAccount, including without limitation, any interruption, omission, mistake, malfunction or delay related thereto. Southwest Gas makes no representation that any data posted is suitable for any particular purpose or use. You should not assume that the information within the Online Services is constantly updated or otherwise includes recent information. All information contained in the Online Services is provided "as is" and "as available," although Southwest Gas will use its reasonable efforts to post the best data that is readily available. Some of the information presented within the Online Services is based on estimates and projections. Southwest Gas reserves the right in its sole opinion to prevent any user from accessing its Online Services in connection with the Online Services.</p>
                        <p>The Online Services will be operated and used at all times subject to applicable laws, rules, regulations and decisions of federal and state governmental authorities having jurisdiction, as in effect from time to time, including without limitation, the applicable public utilities commission.</p>
                        <p>Any dispute related to the Online Services shall be resolved pursuant to the laws of the State of Nevada, without reference to its principles on conflicts of laws.</p>
                        <p>Southwest Gas' currently-authorized California Gas Tariff is hereby incorporated by reference for all California customer accounts. The Company's currently-authorized Nevada Gas Tariff is hereby incorporated by reference for all Nevada customer accounts. The Company's currently-authorized Arizona Gas Tariff is hereby incorporated by reference for all Arizona customer accounts. If any part of this Agreement conflicts with the applicable tariff, the terms of the tariff shall control. No action by you or the Company may amend, supplement, change, or replace any part of this Agreement or tariff that is incorporated by reference. All currently-authorized tariffs can be viewed at <a aria-label="Navigate to rates and regulation" href="https://www.swgas.com/en/rates-and-regulation">https://www.swgas.com/en/rates-and-regulation</a>.</p>
                        <p>Your use of the Online Services does not provide any legal right or interest in any intellectual property used in connection therewith, or derived there from or any text or other content posted in connection therewith, including without limitation any copyright, for which all rights are reserved by Southwest Gas.</p>
                        <p>Use of the Online Services, and any Southwest Gas service accessed, is at your sole risk. Although Southwest Gas has endeavored to create a secure and reliable service, the confidentiality or security of any communication transmitted or accessible over the internet cannot be guaranteed. Southwest Gas does encrypt your personal information on our systems and in transmission and complies with all applicable laws in handling such information. Accordingly, Southwest Gas and its affiliates are not responsible for the security of any information transmitted or accessed using the internet. Actual or attempted unauthorized use of the Online Services may result in criminal and/or civil prosecution.</p>
                        <p>Southwest Gas' use of your information shall be in accordance with Southwest Gas' Privacy Policy which may be viewed at <a aria-label="Navigate to privacy policy" href="https://www.swgas.com/en/privacy-policy">https://www.swgas.com/en/privacy-policy</a>. We may share information we collect about you, except credit bureau information, with outside companies that are assisting us with servicing your account. Our agreements with these outside companies (service providers) require that they protect this information; they are only authorized to use such information to carry out the services they are performing for Southwest Gas.</p>
                        <p>Southwest Gas shall not be deemed to have waived any of its rights or remedies hereunder unless such waiver is in writing and signed by Southwest Gas. No delay or omission on the part of Southwest Gas in exercising any rights or remedies shall operate as a waiver of such rights or remedies or any other rights or remedies. A waiver on any one occasion shall not be construed as a bar or waiver of any rights or remedies on future occasions.</p>
                        <p>Southwest Gas reserves the right to change any terms and conditions of the Online Services. You can review the most current version of the applicable terms and conditions at any time by visiting <a aria-label="Navigate to terms" href="https://myaccount.swgas.com/content/terms">https://myaccount.swgas.com/content/terms</a>. Updates or changes to the terms and conditions of the Online Services will be effective when posted on this site. Your continued use of this site or any services provided hereunder after any changes in such terms and conditions shall constitute your consent to such changes. Southwest Gas reserves the right to change, modify or discontinue, temporarily or permanently, the site or any portion thereof, without notice. You agree that Southwest Gas shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Online Services.</p>
                        <p>Additional terms and conditions may apply to a specific service provided hereunder.</p>
                        <p>These Terms and Conditions do not supersede, modify or in any way mitigate your obligation to be bound by and comply with all applicable tariffs, rules and regulations related to your service.</p>
                        <p>SOUTHWEST GAS SHALL NOT BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES OR FOR THE LOSS OF PROFIT, REVENUE OR DATA WHICH ARISE FROM OR IS RELATED TO THE USE OF THE ONLINE SERVICES PROVIDED TO YOU THEREUNDER. IN ADDITION, YOU AGREE TO INDEMNIFY AND HOLD SOUTHWEST GAS HARMLESS FROM ANY ACTIONS, CLAIMS, DAMAGES, LIABILITIES OR LOSSES ARISING FROM OR RELATED TO THE USE OF THE ONLINE SERVICES.</p>
                        <h3>Dispute Resolution</h3>
                        <ol type="A">
                            <li><u>ALL DISPUTES ARISING OR RELATED TO THIS AGREEMENT OR ANY ASPECT OF THE RELATIONSHIP BETWEEN YOU, ON THE ONE HAND, AND THE COMPANY, ITS PARENT OR SUBSIDIARY COMPANIES, ITS SUPPLIERS OR ITS VENDORS, ON THE OTHER HAND, WHETHER BASED IN CONTRACT, TORT, STATUTE, FRAUD, MISREPRESENTATION, OR ANY OTHER LEGAL THEORY, WILL BE RESOLVED THROUGH FINAL AND BINDING RESOLUTION BEFORE THE CALIFORNIA PUBLIC UTILITIES COMMISSION, THE PUBLIC UTILITIES COMMISSION OF NEVADA, OR THE ARIZONA CORPORATION COMMISSION, AS APPLICABLE. YOU AGREE THAT SOUTHWEST GAS AND YOU ARE EACH WAIVING THE RIGHT TO TRIAL BY A JURY. YOU AGREE THAT ANY DISPUTE UNDER THIS AGREEMENT WILL TAKE PLACE ON AN INDIVIDUAL BASIS; CLASS ACTIONS ARE NOT PERMITTED AND YOU ARE AGREEING TO GIVE UP THE ABILITY TO PARTICIPATE IN A CLASS ACTION.</u></li>
                            <li><u>TO THE EXTENT THE FOREGOING CLAUSE IS DETERMINED TO BE INVALID OR UNENFORCEABLE BY A COURT, THEN IN THAT EVENT, AND EXCEPT FOR DISPUTES THAT QUALIFY FOR SMALL CLAIMS COURT, ALL DISPUTES ARISING OUT OF OR RELATED TO THIS AGREEMENT OR ANY ASPECT OF THE RELATIONSHIP BETWEEN YOU, ON THE ONE HAND, AND THE COMPANY, ITS PARENT OR SUBSIDIARY COMPANIES, ITS SUPPLIERS OR ITS VENDORS, ON THE OTHER HAND, WHETHER BASED IN CONTRACT, TORT, STATUTE, FRAUD, MISREPRESENTATION, OR ANY OTHER LEGAL THEORY, WILL BE RESOLVED THROUGH FINAL AND BINDING ARBITRATION BEFORE A NEUTRAL ARBITRATOR INSTEAD OF IN A COURT BY A JUDGE OR JURY AND YOU AGREE THAT SOUTHWEST GAS AND YOU ARE EACH WAIVING THE RIGHT TO TRIAL BY A JURY. YOU AGREE THAT ANY ARBITRATION UNDER THIS AGREEMENT WILL TAKE PLACE ON AN INDIVIDUAL BASIS; CLASS ARBITRATIONS AND CLASS ACTIONS ARE NOT PERMITTED AND YOU ARE AGREEING TO GIVE UP THE ABILITY TO PARTICIPATE IN A CLASS ACTION.</u></li>
                            <li>Any arbitration conducted pursuant to Paragraph "B" of this section will be administered by the American Arbitration Association ("AAA") under its Consumer Arbitration Rules (currently available at <a aria-label="Navigate to other link" href="https://www.adr.org/aaa/faces/rules/searchrules/rulesdetail?doc=ADRSTAGE2021424)">https://www.adr.org/aaa/faces/rules/searchrules/rulesdetail?doc=ADRSTAGE2021424)</a>, as amended by this Agreement. The arbitrator will conduct hearings, if any, by teleconference or videoconference, rather than by personal appearances, unless the arbitrator determines upon request by you or by us that an in-person hearing is appropriate. Any in-person appearances will be held at a location which is reasonably convenient to both parties with due consideration of their ability to travel and other pertinent circumstances. If the parties are unable to agree on a location, such determination should be made by the AAA or by the arbitrator. If you are able to demonstrate that the costs of arbitration will be prohibitive as compared to the costs of litigation, the Company will pay as much of your filing and hearing fees in connection with the arbitration as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive. The arbitrator's decision will follow the terms of this Agreement and will be final and binding. The arbitrator will have authority to award temporary, interim, or permanent injunctive relief, or relief providing for specific performance of this Agreement, but only to the extent necessary to provide relief warranted by the individual claim before the arbitrator. The award rendered by the arbitrator may be confirmed and enforced in any court having jurisdiction thereof. With the exception of any of the language above in this paragraph B of the Dispute Resolution provision relating to the waiver of class and representative actions, if a court decides that any part of this Dispute Resolution provision is invalid or unenforceable, the other parts of this Dispute Resolution provision shall still apply. If a court decides that any aspect of the language above in this paragraph B of the Dispute Resolution provision relating to the waiver of class and representative actions is invalid or unenforceable, then the entirety of this Dispute Resolution provision shall be null and void. The remainder of the Agreement will continue to apply and be unaffected by this severability provision.</li>
                            <li>Notwithstanding any of the foregoing, nothing in this Agreement will preclude you from bringing issues to the attention of federal, state, or local agencies and, if the law allows, they can seek relief against us on your behalf.</li>
                        </ol>
                        <h2>Attorney's Fees</h2>
                        <p>You and the Company agree that should legal proceedings be commenced concerning any provision of these Terms and Conditions or relative to the subject matter hereof, no party shall be entitled to an award of costs and attorney's fees incurred in connection with the prosecution or defense of such action.</p>
                        <p><strong>I HAVE READ AND UNDERSTAND THE FOREGOING AGREEMENT AND AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS.</strong></p>
                    </MDBCol>
                </MDBRow>
            </MDBContainer>
        </Dialog>
    )
}
export default Term1;
